# Pandas

In [2]:
import pandas as pd

In [3]:



print()
print(" Series vs DataFrame")
print("="*50)
print()

age = pd.Series([11,22,33])
print("A series:   ", age)

 Series vs DataFrame
==================================================

A series:    0    11
1    22
2    33
dtype: int64

In [ ]:
# An object
age = pd.Series([11, "same", False])
age

0       11
1     same
2    False
dtype: object

In [8]:
age = pd.Series([11, "same", False], index=['a','b','c'])
age

a       11
b     same
c    False
dtype: object

In [13]:
# data frame
studentInfo = pd.DataFrame({
    'name':["sama", "Ahmed","Omer"], # string
    'age':[21,22,23], # int
    'isGraduated':[True,True,False] # bool
    
}, index=['a','b','c'])
studentInfo

    name  age  isGraduated
a   sama   21         True
b  Ahmed   22         True
c   Omer   23        False

In [4]:
# File -> Data
df = pd.read_csv('./FINAL_DATASET.csv')
df

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,1,https://images.unsplash.com/photo-172422561835...,REAL,1,Authentic,Female,18-25,Unsplash,NaN,High,1080x1080,0.96,Easy,train,2026-04-24,v2.0,2026
1,2,https://images.unsplash.com/photo-172422561873...,REAL,1,Authentic,Male,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,train,2026-04-04,v2.0,2026
2,3,https://images.unsplash.com/photo-172422561834...,REAL,1,Authentic,Female,36-50,Unsplash,NaN,High,1080x1080,0.95,Easy,test,2026-02-07,v2.0,2026
3,4,https://images.unsplash.com/photo-172422561855...,REAL,1,Authentic,Female,26-35,Unsplash,NaN,High,1080x1080,0.89,Easy,train,2026-02-20,v2.0,2026
4,5,https://images.unsplash.com/photo-172422561823...,REAL,1,Authentic,Male,36-50,Unsplash,NaN,High,1080x1080,0.86,Easy,train,2026-04-12,v2.0,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6552,6553,https://api.multiavatar.com/face996.jpg,FAKE,0,AI Generated,Unknown,18-25,MultiSource,StyleGAN3,High,1024x1024,0.85,Hard,train,2026-01-12,v2.0,2026
6553,6554,https://api.multiavatar.com/face997.jpg,FAKE,0,AI Generated,Unknown,50+,MultiSource,StyleGAN3,High,1024x1024,0.96,Hard,train,2026-01-07,v2.0,2026
6554,6555,https://api.multiavatar.com/face998.jpg,FAKE,0,AI Generated,Unknown,18-25,MultiSource,StyleGAN3,High,1024x1024,0.91,Medium,train,2026-04-24,v2.0,2026
6555,6556,https://api.multiavatar.com/face999.jpg,FAKE,0,AI Generated,Unknown,26-35,MultiSource,StyleGAN3,High,1024x1024,0.86,Medium,train,2026-01-24,v2.0,2026
6556,6557,https://api.multiavatar.com/face1000.jpg,FAKE,0,AI Generated,Unknown,36-50,MultiSource,StyleGAN3,Medium,1024x1024,0.93,Hard,val,2026-03-12,v2.0,2026

In [ ]:
# A column
print(df['category'])

0          Authentic
1          Authentic
2          Authentic
3          Authentic
4          Authentic
            ...
6552    AI Generated
6553    AI Generated
6554    AI Generated
6555    AI Generated
6556    AI Generated
Name: category, Length: 6557, dtype: str

In [ ]:
# More than 1 column
print(df[['category','gender']])

          category   gender
0        Authentic   Female
1        Authentic     Male
2        Authentic   Female
3        Authentic   Female
4        Authentic     Male
...            ...      ...
6552  AI Generated  Unknown
6553  AI Generated  Unknown
6554  AI Generated  Unknown
6555  AI Generated  Unknown
6556  AI Generated  Unknown

[6557 rows x 2 columns]

In [ ]:
# Row [n] iloc takes the index ignoring the naming
df.iloc[10]

image_id                                                               11
image_url               https://images.unsplash.com/photo-172422561812...
label                                                                REAL
label_numeric                                                           1
category                                                        Authentic
gender                                                            Unknown
age_group                                                           26-35
source                                                           Unsplash
fake_method                                                           NaN
image_quality                                                        High
resolution                                                      1080x1080
confidence_score                                                     0.97
detection_difficulty                                                 Easy
dataset_split                                                       train
date_collected                                                 2026-02-13
version                                                              v2.0
year                                                                 2026
Name: 10, dtype: object

In [ ]:
# index depending on the real index name  
# loc [ R. labelName]
df.loc[10]

image_id                                                               11
image_url               https://images.unsplash.com/photo-172422561812...
label                                                                REAL
label_numeric                                                           1
category                                                        Authentic
gender                                                            Unknown
age_group                                                           26-35
source                                                           Unsplash
fake_method                                                           NaN
image_quality                                                        High
resolution                                                      1080x1080
confidence_score                                                     0.97
detection_difficulty                                                 Easy
dataset_split                                                       train
date_collected                                                 2026-02-13
version                                                              v2.0
year                                                                 2026
Name: 10, dtype: object

In [19]:
# iloc [R,C]
df.iloc[0,5]

'Female'

In [ ]:
# All first n elements / ending not included
df.iloc[3:10]

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
3,4,https://images.unsplash.com/photo-172422561855...,REAL,1,Authentic,Female,26-35,Unsplash,NaN,High,1080x1080,0.89,Easy,train,2026-02-20,v2.0,2026
4,5,https://images.unsplash.com/photo-172422561823...,REAL,1,Authentic,Male,36-50,Unsplash,NaN,High,1080x1080,0.86,Easy,train,2026-04-12,v2.0,2026
5,6,https://images.unsplash.com/photo-172422561869...,REAL,1,Authentic,Unknown,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,val,2026-04-23,v2.0,2026
6,7,https://images.unsplash.com/photo-165740366923...,REAL,1,Authentic,Male,26-35,Unsplash,NaN,Medium,1080x1080,0.87,Easy,test,2026-03-09,v2.0,2026
7,8,https://images.unsplash.com/photo-172422561885...,REAL,1,Authentic,Unknown,18-25,Unsplash,NaN,High,1080x1080,0.88,Easy,val,2026-04-05,v2.0,2026
8,9,https://images.unsplash.com/photo-172422561833...,REAL,1,Authentic,Male,26-35,Unsplash,NaN,High,1080x1080,0.94,Easy,train,2026-02-26,v2.0,2026
9,10,https://images.unsplash.com/photo-172422561873...,REAL,1,Authentic,Unknown,26-35,Unsplash,NaN,High,1080x1080,0.88,Easy,train,2026-02-09,v2.0,2026

In [ ]:
# Condition - filter df[df[condition]]
df[df['confidence_score'] > 0.89]

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,1,https://images.unsplash.com/photo-172422561835...,REAL,1,Authentic,Female,18-25,Unsplash,NaN,High,1080x1080,0.96,Easy,train,2026-04-24,v2.0,2026
1,2,https://images.unsplash.com/photo-172422561873...,REAL,1,Authentic,Male,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,train,2026-04-04,v2.0,2026
2,3,https://images.unsplash.com/photo-172422561834...,REAL,1,Authentic,Female,36-50,Unsplash,NaN,High,1080x1080,0.95,Easy,test,2026-02-07,v2.0,2026
5,6,https://images.unsplash.com/photo-172422561869...,REAL,1,Authentic,Unknown,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,val,2026-04-23,v2.0,2026
8,9,https://images.unsplash.com/photo-172422561833...,REAL,1,Authentic,Male,26-35,Unsplash,NaN,High,1080x1080,0.94,Easy,train,2026-02-26,v2.0,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6548,6549,https://api.multiavatar.com/face992.jpg,FAKE,0,AI Generated,Unknown,36-50,MultiSource,StyleGAN3,Medium,1024x1024,0.96,Medium,train,2026-04-27,v2.0,2026
6549,6550,https://api.multiavatar.com/face993.jpg,FAKE,0,AI Generated,Unknown,50+,MultiSource,StyleGAN3,Medium,1024x1024,0.97,Medium,train,2026-04-06,v2.0,2026
6553,6554,https://api.multiavatar.com/face997.jpg,FAKE,0,AI Generated,Unknown,50+,MultiSource,StyleGAN3,High,1024x1024,0.96,Hard,train,2026-01-07,v2.0,2026
6554,6555,https://api.multiavatar.com/face998.jpg,FAKE,0,AI Generated,Unknown,18-25,MultiSource,StyleGAN3,High,1024x1024,0.91,Medium,train,2026-04-24,v2.0,2026
6556,6557,https://api.multiavatar.com/face1000.jpg,FAKE,0,AI Generated,Unknown,36-50,MultiSource,StyleGAN3,Medium,1024x1024,0.93,Hard,val,2026-03-12,v2.0,2026

In [ ]:
# at == loc [R, labelName]
# iat == iloc [R, C ]
# at + iat faster 
df.iat[0,5]

'Female'