# Pandas

In [4]:
import pandas as pd

In [5]:



print()
print(" Series vs DataFrame")
print("="*50)
print()

age = pd.Series([11,22,33])
print("A series:   ", age)

 Series vs DataFrame
==================================================

A series:    0    11
1    22
2    33
dtype: int64

In [6]:
# An object
age = pd.Series([11, "same", False])
age

0       11
1     same
2    False
dtype: object

In [7]:
age = pd.Series([11, "same", False], index=['a','b','c'])
age

a       11
b     same
c    False
dtype: object

In [59]:
# data frame
studentInfo = pd.DataFrame({
    'name':["sama", "Ahmed","Omer"], # string
    'age':[21,22,23], # int
    'isGraduated':[True,True,False] # bool
    
}, index=['a','b','c'])
studentInfo

    name  age  isGraduated
a   sama   21         True
b  Ahmed   22         True
c   Omer   23        False

In [60]:
# File -> Data
df = pd.read_csv('./FINAL_DATASET.csv')
df

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,1,https://images.unsplash.com/photo-172422561835...,REAL,1,Authentic,Female,18-25,Unsplash,NaN,High,1080x1080,0.96,Easy,train,2026-04-24,v2.0,2026
1,2,https://images.unsplash.com/photo-172422561873...,REAL,1,Authentic,Male,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,train,2026-04-04,v2.0,2026
2,3,https://images.unsplash.com/photo-172422561834...,REAL,1,Authentic,Female,36-50,Unsplash,NaN,High,1080x1080,0.95,Easy,test,2026-02-07,v2.0,2026
3,4,https://images.unsplash.com/photo-172422561855...,REAL,1,Authentic,Female,26-35,Unsplash,NaN,High,1080x1080,0.89,Easy,train,2026-02-20,v2.0,2026
4,5,https://images.unsplash.com/photo-172422561823...,REAL,1,Authentic,Male,36-50,Unsplash,NaN,High,1080x1080,0.86,Easy,train,2026-04-12,v2.0,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6552,6553,https://api.multiavatar.com/face996.jpg,FAKE,0,AI Generated,Unknown,18-25,MultiSource,StyleGAN3,High,1024x1024,0.85,Hard,train,2026-01-12,v2.0,2026
6553,6554,https://api.multiavatar.com/face997.jpg,FAKE,0,AI Generated,Unknown,50+,MultiSource,StyleGAN3,High,1024x1024,0.96,Hard,train,2026-01-07,v2.0,2026
6554,6555,https://api.multiavatar.com/face998.jpg,FAKE,0,AI Generated,Unknown,18-25,MultiSource,StyleGAN3,High,1024x1024,0.91,Medium,train,2026-04-24,v2.0,2026
6555,6556,https://api.multiavatar.com/face999.jpg,FAKE,0,AI Generated,Unknown,26-35,MultiSource,StyleGAN3,High,1024x1024,0.86,Medium,train,2026-01-24,v2.0,2026
6556,6557,https://api.multiavatar.com/face1000.jpg,FAKE,0,AI Generated,Unknown,36-50,MultiSource,StyleGAN3,Medium,1024x1024,0.93,Hard,val,2026-03-12,v2.0,2026

In [61]:
# A column
print(df['category'])

0          Authentic
1          Authentic
2          Authentic
3          Authentic
4          Authentic
            ...
6552    AI Generated
6553    AI Generated
6554    AI Generated
6555    AI Generated
6556    AI Generated
Name: category, Length: 6557, dtype: str

In [62]:
# More than 1 column
print(df[['category','gender']])

          category   gender
0        Authentic   Female
1        Authentic     Male
2        Authentic   Female
3        Authentic   Female
4        Authentic     Male
...            ...      ...
6552  AI Generated  Unknown
6553  AI Generated  Unknown
6554  AI Generated  Unknown
6555  AI Generated  Unknown
6556  AI Generated  Unknown

[6557 rows x 2 columns]

In [63]:
# Row [n] iloc takes the index ignoring the naming
df.iloc[10]

image_id                                                               11
image_url               https://images.unsplash.com/photo-172422561812...
label                                                                REAL
label_numeric                                                           1
category                                                        Authentic
gender                                                            Unknown
age_group                                                           26-35
source                                                           Unsplash
fake_method                                                           NaN
image_quality                                                        High
resolution                                                      1080x1080
confidence_score                                                     0.97
detection_difficulty                                                 Easy
dataset_split                                                       train
date_collected                                                 2026-02-13
version                                                              v2.0
year                                                                 2026
Name: 10, dtype: object

In [64]:
# index depending on the real index name  
# loc [ R. labelName]
df.loc[10]

image_id                                                               11
image_url               https://images.unsplash.com/photo-172422561812...
label                                                                REAL
label_numeric                                                           1
category                                                        Authentic
gender                                                            Unknown
age_group                                                           26-35
source                                                           Unsplash
fake_method                                                           NaN
image_quality                                                        High
resolution                                                      1080x1080
confidence_score                                                     0.97
detection_difficulty                                                 Easy
dataset_split                                                       train
date_collected                                                 2026-02-13
version                                                              v2.0
year                                                                 2026
Name: 10, dtype: object

In [65]:
# iloc [R,C]
df.iloc[0,5]

'Female'

In [66]:
# All first n elements / ending not included
df.iloc[3:10]

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
3,4,https://images.unsplash.com/photo-172422561855...,REAL,1,Authentic,Female,26-35,Unsplash,NaN,High,1080x1080,0.89,Easy,train,2026-02-20,v2.0,2026
4,5,https://images.unsplash.com/photo-172422561823...,REAL,1,Authentic,Male,36-50,Unsplash,NaN,High,1080x1080,0.86,Easy,train,2026-04-12,v2.0,2026
5,6,https://images.unsplash.com/photo-172422561869...,REAL,1,Authentic,Unknown,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,val,2026-04-23,v2.0,2026
6,7,https://images.unsplash.com/photo-165740366923...,REAL,1,Authentic,Male,26-35,Unsplash,NaN,Medium,1080x1080,0.87,Easy,test,2026-03-09,v2.0,2026
7,8,https://images.unsplash.com/photo-172422561885...,REAL,1,Authentic,Unknown,18-25,Unsplash,NaN,High,1080x1080,0.88,Easy,val,2026-04-05,v2.0,2026
8,9,https://images.unsplash.com/photo-172422561833...,REAL,1,Authentic,Male,26-35,Unsplash,NaN,High,1080x1080,0.94,Easy,train,2026-02-26,v2.0,2026
9,10,https://images.unsplash.com/photo-172422561873...,REAL,1,Authentic,Unknown,26-35,Unsplash,NaN,High,1080x1080,0.88,Easy,train,2026-02-09,v2.0,2026

In [67]:
# Condition - filter df[df[condition]]
df[df['confidence_score'] > 0.89]

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,1,https://images.unsplash.com/photo-172422561835...,REAL,1,Authentic,Female,18-25,Unsplash,NaN,High,1080x1080,0.96,Easy,train,2026-04-24,v2.0,2026
1,2,https://images.unsplash.com/photo-172422561873...,REAL,1,Authentic,Male,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,train,2026-04-04,v2.0,2026
2,3,https://images.unsplash.com/photo-172422561834...,REAL,1,Authentic,Female,36-50,Unsplash,NaN,High,1080x1080,0.95,Easy,test,2026-02-07,v2.0,2026
5,6,https://images.unsplash.com/photo-172422561869...,REAL,1,Authentic,Unknown,50+,Unsplash,NaN,High,1080x1080,0.97,Easy,val,2026-04-23,v2.0,2026
8,9,https://images.unsplash.com/photo-172422561833...,REAL,1,Authentic,Male,26-35,Unsplash,NaN,High,1080x1080,0.94,Easy,train,2026-02-26,v2.0,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6548,6549,https://api.multiavatar.com/face992.jpg,FAKE,0,AI Generated,Unknown,36-50,MultiSource,StyleGAN3,Medium,1024x1024,0.96,Medium,train,2026-04-27,v2.0,2026
6549,6550,https://api.multiavatar.com/face993.jpg,FAKE,0,AI Generated,Unknown,50+,MultiSource,StyleGAN3,Medium,1024x1024,0.97,Medium,train,2026-04-06,v2.0,2026
6553,6554,https://api.multiavatar.com/face997.jpg,FAKE,0,AI Generated,Unknown,50+,MultiSource,StyleGAN3,High,1024x1024,0.96,Hard,train,2026-01-07,v2.0,2026
6554,6555,https://api.multiavatar.com/face998.jpg,FAKE,0,AI Generated,Unknown,18-25,MultiSource,StyleGAN3,High,1024x1024,0.91,Medium,train,2026-04-24,v2.0,2026
6556,6557,https://api.multiavatar.com/face1000.jpg,FAKE,0,AI Generated,Unknown,36-50,MultiSource,StyleGAN3,Medium,1024x1024,0.93,Hard,val,2026-03-12,v2.0,2026

In [68]:
# at == loc [R, labelName]
# iat == iloc [R, C ]
# at + iat faster 
df.iat[0,5]

'Female'

In [69]:
# Index range (start, stop, step) Rows
df.index

RangeIndex(start=0, stop=6557, step=1)

In [70]:
# Columns name dtype= "?"
df.columns

Index(['image_id', 'image_url', 'label', 'label_numeric', 'category', 'gender',
       'age_group', 'source', 'fake_method', 'image_quality', 'resolution',
       'confidence_score', 'detection_difficulty', 'dataset_split',
       'date_collected', 'version', 'year'],
      dtype='str')

In [71]:
# Array values
df.values

array([[1,
        'https://images.unsplash.com/photo-1724225618359-a1d2763326f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NDQwMTV8MHwxfHNlYXJjaHwxfHxodW1hbiUyMGZhY2UlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NzgwNjQ2ODd8MA&ixlib=rb-4.1.0&q=80&w=1080',
        'REAL', ..., '2026-04-24', 'v2.0', 2026],
       [2,
        'https://images.unsplash.com/photo-1724225618735-075be4f96a63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NDQwMTV8MHwxfHNlYXJjaHwyfHxodW1hbiUyMGZhY2UlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NzgwNjQ2ODd8MA&ixlib=rb-4.1.0&q=80&w=1080',
        'REAL', ..., '2026-04-04', 'v2.0', 2026],
       [3,
        'https://images.unsplash.com/photo-1724225618348-636d316ef39b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NDQwMTV8MHwxfHNlYXJjaHwzfHxodW1hbiUyMGZhY2UlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NzgwNjQ2ODd8MA&ixlib=rb-4.1.0&q=80&w=1080',
        'REAL', ..., '2026-02-07', 'v2.0', 2026],
       ...,
       [6555, 'https://api.multiavatar.com/face998.jpg', 'FAKE', ...,
        '2026-04-24', 'v2.0', 2026],
       [6556, 'https://api.multiavatar.com/face999.jpg', 'FAKE', ...,
        '2026-01-24', 'v2.0', 2026],
       [6557, 'https://api.multiavatar.com/face1000.jpg', 'FAKE', ...,
        '2026-03-12', 'v2.0', 2026]], shape=(6557, 17), dtype=object)

In [72]:
# Data type
df.dtypes

image_id                  int64
image_url                   str
label                       str
label_numeric             int64
category                    str
gender                      str
age_group                   str
source                      str
fake_method                 str
image_quality               str
resolution                  str
confidence_score        float64
detection_difficulty        str
dataset_split               str
date_collected              str
version                     str
year                      int64
dtype: object

In [73]:
# (R,C) (6557,17)
df.shape

(6557, 17)

In [74]:
# Data frame dim  
# 4 dim means 4 different tables (R,C) inside on array
df.ndim

2

In [75]:
# sum(R.C)
df.size

111469

In [76]:
df.empty

False

In [77]:
# transpose 
df.T

,0,1,2,3,4,5,6,7,8,9,...,6547,6548,6549,6550,6551,6552,6553,6554,6555,6556
image_id,1,2,3,4,5,6,7,8,9,10,...,6548,6549,6550,6551,6552,6553,6554,6555,6556,6557
image_url,https://images.unsplash.com/photo-172422561835...,https://images.unsplash.com/photo-172422561873...,https://images.unsplash.com/photo-172422561834...,https://images.unsplash.com/photo-172422561855...,https://images.unsplash.com/photo-172422561823...,https://images.unsplash.com/photo-172422561869...,https://images.unsplash.com/photo-165740366923...,https://images.unsplash.com/photo-172422561885...,https://images.unsplash.com/photo-172422561833...,https://images.unsplash.com/photo-172422561873...,...,https://api.multiavatar.com/face991.jpg,https://api.multiavatar.com/face992.jpg,https://api.multiavatar.com/face993.jpg,https://api.multiavatar.com/face994.jpg,https://api.multiavatar.com/face995.jpg,https://api.multiavatar.com/face996.jpg,https://api.multiavatar.com/face997.jpg,https://api.multiavatar.com/face998.jpg,https://api.multiavatar.com/face999.jpg,https://api.multiavatar.com/face1000.jpg
label,REAL,REAL,REAL,REAL,REAL,REAL,REAL,REAL,REAL,REAL,...,FAKE,FAKE,FAKE,FAKE,FAKE,FAKE,FAKE,FAKE,FAKE,FAKE
label_numeric,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
category,Authentic,Authentic,Authentic,Authentic,Authentic,Authentic,Authentic,Authentic,Authentic,Authentic,...,AI Generated,AI Generated,AI Generated,AI Generated,AI Generated,AI Generated,AI Generated,AI Generated,AI Generated,AI Generated
gender,Female,Male,Female,Female,Male,Unknown,Male,Unknown,Male,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
age_group,18-25,50+,36-50,26-35,36-50,50+,26-35,18-25,26-35,26-35,...,26-35,36-50,50+,26-35,50+,18-25,50+,18-25,26-35,36-50
source,Unsplash,Unsplash,Unsplash,Unsplash,Unsplash,Unsplash,Unsplash,Unsplash,Unsplash,Unsplash,...,MultiSource,MultiSource,MultiSource,MultiSource,MultiSource,MultiSource,MultiSource,MultiSource,MultiSource,MultiSource
fake_method,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3,StyleGAN3
image_quality,High,High,High,High,High,High,Medium,High,High,High,...,High,Medium,Medium,Medium,High,High,High,High,High,Medium
resolution,1080x1080,1080x1080,1080x1080,1080x1080,1080x1080,1080x1080,1080x1080,1080x1080,1080x1080,1080x1080,...,1024x1024,1024x1024,1024x1024,1024x1024,1024x1024,1024x1024,1024x1024,1024x1024,1024x1024,1024x1024
confidence_score,0.96,0.97,0.95,0.89,0.86,0.97,0.87,0.88,0.94,0.88,...,0.98,0.96,0.97,0.88,0.83,0.85,0.96,0.91,0.86,0.93
detection_difficulty,Easy,Easy,Easy,Easy,Easy,Easy,Easy,Easy,Easy,Easy,...,Medium,Medium,Medium,Medium,Medium,Hard,Hard,Medium,Medium,Hard
dataset_split,train,train,test,train,train,val,test,val,train,train,...,test,train,train,train,train,train,train,train,train,val
date_collected,2026-04-24,2026-04-04,2026-02-07,2026-02-20,2026-04-12,2026-04-23,2026-03-09,2026-04-05,2026-02-26,2026-02-09,...,2026-02-07,2026-04-27,2026-04-06,2026-02-07,2026-01-22,2026-01-12,2026-01-07,2026-04-24,2026-01-24,2026-03-12
version,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,...,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0,v2.0
year,2026,2026,2026,2026,2026,2026,2026,2026,2026,2026,...,2026,2026,2026,2026,2026,2026,2026,2026,2026,2026

In [78]:
# Range + index
df.axes

[RangeIndex(start=0, stop=6557, step=1),
 Index(['image_id', 'image_url', 'label', 'label_numeric', 'category', 'gender',
        'age_group', 'source', 'fake_method', 'image_quality', 'resolution',
        'confidence_score', 'detection_difficulty', 'dataset_split',
        'date_collected', 'version', 'year'],
       dtype='str')]

In [79]:
# empty or missing data -- NaN
df.isna()

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6552,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6553,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6554,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6555,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [80]:
# Not NaN
df = df.notna()
df

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6552,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6553,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6554,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6555,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6556,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [81]:
# Many function at the same time -- summary
df.describe()

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
count,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557,6557
unique,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1
top,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
freq,6557,6557,6557,6557,6557,6557,6557,6557,3767,6557,6557,6557,6557,6557,6557,6557,6557

In [82]:
# array info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6557 entries, 0 to 6556
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   image_id              6557 non-null   bool
 1   image_url             6557 non-null   bool
 2   label                 6557 non-null   bool
 3   label_numeric         6557 non-null   bool
 4   category              6557 non-null   bool
 5   gender                6557 non-null   bool
 6   age_group             6557 non-null   bool
 7   source                6557 non-null   bool
 8   fake_method           6557 non-null   bool
 9   image_quality         6557 non-null   bool
 10  resolution            6557 non-null   bool
 11  confidence_score      6557 non-null   bool
 12  detection_difficulty  6557 non-null   bool
 13  dataset_split         6557 non-null   bool
 14  date_collected        6557 non-null   bool
 15  version               6557 non-null   bool
 16  year                  6557 non-null   bool
dtypes: bool(17)
memory usage: 109.0 KB

In [83]:
# the first 2 rows
df.head(2)

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True

In [84]:
# The last 2 rows
df.tail(2)

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
6555,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6556,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [85]:
# Selecting data
df['gender']

0       True
1       True
2       True
3       True
4       True
        ...
6552    True
6553    True
6554    True
6555    True
6556    True
Name: gender, Length: 6557, dtype: bool

In [86]:
# Series
type(df['gender'])

pandas.Series

In [87]:
#
type(df[['gender']])

pandas.DataFrame

In [88]:
# 2 columns
df[['gender', 'category']]

      gender  category
0       True      True
1       True      True
2       True      True
3       True      True
4       True      True
...      ...       ...
6552    True      True
6553    True      True
6554    True      True
6555    True      True
6556    True      True

[6557 rows x 2 columns]

In [89]:
#
df.isnull().sum()

image_id                0
image_url               0
label                   0
label_numeric           0
category                0
gender                  0
age_group               0
source                  0
fake_method             0
image_quality           0
resolution              0
confidence_score        0
detection_difficulty    0
dataset_split           0
date_collected          0
version                 0
year                    0
dtype: int64

In [90]:
# Sorting default is descending
df.sort_values(by='age_group', ascending=False)

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
4368,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4378,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4377,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4376,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2183,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
2182,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
2181,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
2180,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True
6556,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True